Exercíco

Em grupo para os data sets:

X -> tempo médio de espera do Uber por distrito da cidade de São Paulo

y -> renda média percapta distrito da cidade de São Paulo

Faça uma rede neural utlizando regressão linear simples, rode para 1500, 2500, 3500 e 5000 épocas.

Compare os erros MAE e MSE de cada rodada escolha o melhor modelo e justifique

"X = np.array([[188], [185], [471], [188], [183],[196],[183],[204],[211],[221],[494],[243],[417],[197],[187],[213],[219],[249],[220],[175],[193],[230],[268],[218],[279],[187],[223],[234],[222],[575],[245],[381],[187],[185],[220],[188],[208],[220],[220],[219],[352],[357],[232],[182],[307],[259],[231],[187],[191],[200],[354],[971],[180],[196],[220],[694],[196],[264],[334],[179],[177],[365],[180],[254],[174],[269],[206],[242],[216],[198],[197],[199],[240],[207],[214],[199],[315],[217],[173],[231],[219],[173],[499],[199],[227],[201],[192],[188],[197],[208],[199],[179],[175],[191],[199],[218]]"

"y = np.array ([[1355],[3984],[528],[795],[740],[2698],[2546],[1319],[933],[969],[502],[2106],[689],[1722],[3231],[1769],[722],[690],[541],[1236],[1128],[649],[687],[690],[407],[3788],[1488],[635],[976],[451],[516],[426],[1527],[4134],[435],[620],[1233],[708],[980],[1212],[558],[427],[416],[4707],[599],[570],[412],[2463],[2102],[958],[1265],[347],[4968],[1892],[4085],[404],[963],[673],[524],[1030],[3300],[473],[3727],[965],[772],[791],[1530],[1349],[913],[2230],[2026],[3034],[931],[880],[608],[602],[452],[545],[2570],[909],[1868],[2159],[720],[1279],[1960],[503],[1260],[1212],[538],[2943],[822],[3757],[986],[724],[1188],[1759]]"



In [13]:
import numpy as np
X = np.array([[188], [185], [471], [188], [183],[196],[183],[204],[211],[221],[494],[243],[417],[197],[187],[213],[219],[249],[220],[175],[193],[230],[268],[218],[279],[187],[223],[234],[222],[575],[245],[381],[187],[185],[220],[188],[208],[220],[220],[219],[352],[357],[232],[182],[307],[259],[231],[187],[191],[200],[354],[971],[180],[196],[220],[694],[196],[264],[334],[179],[177],[365],[180],[254],[174],[269],[206],[242],[216],[198],[197],[199],[240],[207],[214],[199],[315],[217],[173],[231],[219],[173],[499],[199],[227],[201],[192],[188],[197],[208],[199],[179],[175],[191],[199],[218]])
y = np.array ([[1355],[3984],[528],[795],[740],[2698],[2546],[1319],[933],[969],[502],[2106],[689],[1722],[3231],[1769],[722],[690],[541],[1236],[1128],[649],[687],[690],[407],[3788],[1488],[635],[976],[451],[516],[426],[1527],[4134],[435],[620],[1233],[708],[980],[1212],[558],[427],[416],[4707],[599],[570],[412],[2463],[2102],[958],[1265],[347],[4968],[1892],[4085],[404],[963],[673],[524],[1030],[3300],[473],[3727],[965],[772],[791],[1530],[1349],[913],[2230],[2026],[3034],[931],[880],[608],[602],[452],[545],[2570],[909],[1868],[2159],[720],[1279],[1960],[503],[1260],[1212],[538],[2943],[822],[3757],[986],[724],[1188],[1759]])


Para trabalhar com regressão e redes neurais pracisamos fazer a padronização da das variáveis de entrada, todas precisam estar na mesma escala.

In [14]:
from sklearn.preprocessing import StandardScaler
# chamando a lib StandardScaler podemos usar o metodo fit_transform que irá padronizar as variáveis 
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)

In [15]:
X

array([[-0.5143737 ],
       [-0.54026771],
       [ 1.9282945 ],
       [-0.5143737 ],
       [-0.55753039],
       [-0.44532301],
       [-0.55753039],
       [-0.37627232],
       [-0.31585297],
       [-0.2295396 ],
       [ 2.12681524],
       [-0.0396502 ],
       [ 1.46220233],
       [-0.43669168],
       [-0.52300504],
       [-0.29859029],
       [-0.24680228],
       [ 0.01213782],
       [-0.23817094],
       [-0.62658108],
       [-0.47121702],
       [-0.15185757],
       [ 0.17613321],
       [-0.25543361],
       [ 0.27107791],
       [-0.52300504],
       [-0.21227693],
       [-0.11733223],
       [-0.22090827],
       [ 2.82595348],
       [-0.02238753],
       [ 1.15147422],
       [-0.52300504],
       [-0.54026771],
       [-0.23817094],
       [-0.5143737 ],
       [-0.34174698],
       [-0.23817094],
       [-0.23817094],
       [-0.24680228],
       [ 0.90116547],
       [ 0.94432215],
       [-0.1345949 ],
       [-0.56616172],
       [ 0.51275533],
       [ 0

In [16]:
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

In [17]:
y

array([[-0.03186385],
       [ 2.38095499],
       [-0.79086011],
       [-0.54581537],
       [-0.59629275],
       [ 1.20070203],
       [ 1.06120091],
       [-0.06490359],
       [-0.41916303],
       [-0.38612329],
       [-0.81472215],
       [ 0.65738185],
       [-0.64309905],
       [ 0.30495795],
       [ 1.68987375],
       [ 0.34809317],
       [-0.61281262],
       [-0.64218128],
       [-0.77892909],
       [-0.14107855],
       [-0.24019777],
       [-0.67980987],
       [-0.64493459],
       [-0.64218128],
       [-0.90191035],
       [ 2.20107196],
       [ 0.09019964],
       [-0.69265866],
       [-0.37969889],
       [-0.86152844],
       [-0.80187336],
       [-0.88447271],
       [ 0.12599269],
       [ 2.51862058],
       [-0.87621277],
       [-0.70642522],
       [-0.14383186],
       [-0.62566141],
       [-0.37602781],
       [-0.16310504],
       [-0.76332699],
       [-0.88355494],
       [-0.89365042],
       [ 3.04450311],
       [-0.7256984 ],
       [-0

In [18]:
import pandas as pd

dfx = pd.DataFrame(X, columns=['X'])

dfy = pd.DataFrame(y, columns=['y'])
dfy.to_csv('y_scaler')
dfx.to_csv('x_scaler')

In [19]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.scatter(X,y)

## Fórmula da regressão linear simples

y = b0 + b1*x

O objetivo de uma regressão linear simples é encontar os coeficientes da relação, ou seja, b0 e b1, a rede neural treinada por varias épocas testará varios coeficientes diferentes e com o auxilio do losserror e da função de otmização da descida do gradiente ela tende a convergir para a solução ótima   

In [25]:
# sorteia aleatoriamente com uma semente para repetir os resultados futuramente
np.random.seed(0)
np.random.rand(2)

array([0.5488135 , 0.71518937])

In [26]:
import tensorflow as tf
# faz o compilador se comportar como TF_V1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [27]:
# inicio as duas variááveis com valores aleatóórios 
b0 = tf.Variable(0.54)
b1 = tf.Variable(0.71)

In [28]:


# diferente da rede neural em camadas, uma rede neural que simula uma regressão linear precisa apenas de uma camada onde a função 
# de perda é calculada a partir da equacão teorica da regreção y = b0 + b1*x
erro = tf.losses.mean_squared_error(y, (b0 + b1 * X))


# calcula os novos pesos para a rede (descida do gradiente) o parametro learning_rate é a taxa de aprendizado (obs: normalmente utilizamos 0,001)
otimizador = tf.train.GradientDescentOptimizer(learning_rate = 0.001)

# programa o treinamento da rede
treinamento = otimizador.minimize(erro)
init = tf.global_variables_initializer()

In [38]:
with tf.Session() as sess:
    sess.run(init)
    #for i in range(1000):
    for i in range(10000):
        sess.run(treinamento)
    b0_final, b1_final = sess.run([b0, b1])

In [39]:
b0_final

1.180223e-09

In [40]:
b1_final

-0.36034748

In [41]:
# faço a conta com a fórmula da regressão
previsoes = b0_final + b1_final * X
previsoes

array([[ 0.18535327],
       [ 0.19468411],
       [-0.69485606],
       [ 0.18535327],
       [ 0.20090467],
       [ 0.16047103],
       [ 0.20090467],
       [ 0.13558878],
       [ 0.11381682],
       [ 0.08271402],
       [-0.76639251],
       [ 0.01428785],
       [-0.52690092],
       [ 0.15736075],
       [ 0.18846355],
       [ 0.10759626],
       [ 0.08893458],
       [-0.00437383],
       [ 0.0858243 ],
       [ 0.22578691],
       [ 0.16980187],
       [ 0.0547215 ],
       [-0.06346916],
       [ 0.09204486],
       [-0.09768224],
       [ 0.18846355],
       [ 0.07649346],
       [ 0.04228037],
       [ 0.07960374],
       [-1.01832521],
       [ 0.00806729],
       [-0.41493083],
       [ 0.18846355],
       [ 0.19468411],
       [ 0.0858243 ],
       [ 0.18535327],
       [ 0.12314766],
       [ 0.0858243 ],
       [ 0.0858243 ],
       [ 0.08893458],
       [-0.3247327 ],
       [-0.3402841 ],
       [ 0.04850093],
       [ 0.20401495],
       [-0.18477009],
       [-0

In [42]:
plt.plot(X, previsoes, color = 'red')
plt.plot(X, y, 'o')

In [24]:
# desnormaliza os dados voltando para escala original 
y1 = scaler_y.inverse_transform(y)
y1

array([[1355.],
       [3984.],
       [ 528.],
       [ 795.],
       [ 740.],
       [2698.],
       [2546.],
       [1319.],
       [ 933.],
       [ 969.],
       [ 502.],
       [2106.],
       [ 689.],
       [1722.],
       [3231.],
       [1769.],
       [ 722.],
       [ 690.],
       [ 541.],
       [1236.],
       [1128.],
       [ 649.],
       [ 687.],
       [ 690.],
       [ 407.],
       [3788.],
       [1488.],
       [ 635.],
       [ 976.],
       [ 451.],
       [ 516.],
       [ 426.],
       [1527.],
       [4134.],
       [ 435.],
       [ 620.],
       [1233.],
       [ 708.],
       [ 980.],
       [1212.],
       [ 558.],
       [ 427.],
       [ 416.],
       [4707.],
       [ 599.],
       [ 570.],
       [ 412.],
       [2463.],
       [2102.],
       [ 958.],
       [1265.],
       [ 347.],
       [4968.],
       [1892.],
       [4085.],
       [ 404.],
       [ 963.],
       [ 673.],
       [ 524.],
       [1030.],
       [3300.],
       [ 473.],
       [

In [25]:
# desnormaliza os dados voltando para escala original 
previsoes1 = scaler_y.inverse_transform(previsoes)
previsoes1

array([[1.59012894e+03],
       [1.59621719e+03],
       [1.01580435e+03],
       [1.59012894e+03],
       [1.60027602e+03],
       [1.57389362e+03],
       [1.60027602e+03],
       [1.55765829e+03],
       [1.54345239e+03],
       [1.52315823e+03],
       [9.69127792e+02],
       [1.47851109e+03],
       [1.12539279e+03],
       [1.57186420e+03],
       [1.59215836e+03],
       [1.53939355e+03],
       [1.52721706e+03],
       [1.46633460e+03],
       [1.52518765e+03],
       [1.61651134e+03],
       [1.57998187e+03],
       [1.50489349e+03],
       [1.42777570e+03],
       [1.52924648e+03],
       [1.40545213e+03],
       [1.59215836e+03],
       [1.51909940e+03],
       [1.49677583e+03],
       [1.52112882e+03],
       [8.04745135e+02],
       [1.47445226e+03],
       [1.19845175e+03],
       [1.59215836e+03],
       [1.59621719e+03],
       [1.52518765e+03],
       [1.59012894e+03],
       [1.54954063e+03],
       [1.52518765e+03],
       [1.52518765e+03],
       [1.52721706e+03],


In [ ]:
# calcula os erros do modelo 
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y1, previsoes1)
mse = mean_squared_error(y1, previsoes1)

In [ ]:
#Mean absolute error – MAE
mae

787.1664928744034

In [ ]:
#Mean squared error – MSE
mse

1033054.0799038172