variavel_1 | variavel_2 | resultado esperado
---------  | ---------  |  ---------
     0    |      0     |           1
     0    |       1     |           0
     1    |       0     |           0
     0    |       0     |           1

In [ ]:
pip install tensorflow

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])

X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
y = np.array([[1], [0], [0], [1]])
y

array([[1],
       [0],
       [0],
       [1]])

In [5]:
neuronio_entrada = 2
neuronio_oculta = 3
neuronio_saida = 1

In [6]:
W = {'oculta': tf.Variable(tf.random.normal([neuronio_entrada, neuronio_oculta]), name='w_oculta'),
     'saida': tf.Variable(tf.random.normal([neuronio_oculta, neuronio_saida]), name= 'w_saida')
     }

In [7]:
type(W)
type(W['oculta'])
W['oculta']
W['saida']

<tf.Variable 'w_saida:0' shape=(3, 1) dtype=float32_ref>

In [8]:
b = {'oculta': tf.Variable(tf.random.normal([neuronio_oculta]), name='b_oculta'),
     'saida': tf.Variable(tf.random.normal([neuronio_saida]), name='b_saida')
     }

In [9]:
xph = tf.placeholder(tf.float32, [4, neuronio_entrada], name='xph')
yph = tf.placeholder(tf.float32, [4, neuronio_saida], name='yph')



In [10]:
camada_oculta = tf.add(tf.matmul(xph, W['oculta']), b['oculta'])
camada_oculta_ativacao = tf.sigmoid(camada_oculta)
camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
camada_saida_ativacao = tf.sigmoid(camada_saida)

erro = tf.losses.mean_squared_error(yph, camada_saida_ativacao)

otimizador = tf.train.GradientDescentOptimizer(learning_rate=0.3).minimize(erro)


In [11]:
init = tf.global_variables_initializer()

In [12]:
with tf.Session() as sess:
  sess.run(init)
  for epocas in range(10000):
    erro_medio = 0
    _, custo = sess.run([otimizador, erro], feed_dict = {xph: X, yph: y})
    if epocas % 200 == 0:
      erro_medio += custo/4
      print(erro_medio)
  
  W_final, b_final = sess.run([W, b])

0.09111682325601578
0.062400490045547485
0.06137168034911156
0.060063041746616364
0.05792403966188431
0.054534442722797394
0.04978480190038681
0.04360932856798172
0.035322487354278564
0.02539280243217945
0.016916511580348015
0.011371444910764694
0.008030329830944538
0.0059779975563287735
0.004653455223888159
0.0037537456955760717
0.003114426974207163
0.002642581006512046
0.0022831617388874292
0.0020020550582557917
0.0017772738356143236
0.0015941187739372253
0.0014424542896449566
0.0013151103630661964
0.0012068835785612464
0.001113920472562313
0.0010333149693906307
0.0009628408588469028
0.0009007628541439772
0.0008457099320366979
0.0007965925615280867
0.0007525295950472355
0.0007128011202439666
0.0006768169696442783
0.0006440860452130437
0.0006142001366242766
0.0005868131993338466
0.0005616318085230887
0.0005384095711633563
0.0005169291980564594
0.000497009779792279
0.00047848891699686646
0.0004612308111973107
0.00044511182932183146
0.0004300256841816008
0.0004158796218689531
0.00040258

In [13]:
W_final

{'oculta': array([[-5.312353 , -3.8612218,  4.6707273],
        [-2.8751757, -5.668987 , -5.1804075]], dtype=float32),
 'saida': array([[-7.397238 ],
        [ 8.072645 ],
        [-5.2706604]], dtype=float32)}

In [14]:
b_final

{'oculta': array([ 5.776861 ,  1.9815758, -3.2874038], dtype=float32),
 'saida': array([3.8051622], dtype=float32)}

# Usando o algoritmo

In [15]:
camada_oculta_teste = tf.add(tf.matmul(xph, W_final['oculta']), b_final['oculta'])
camada_oculta_ativacao_teste = tf.sigmoid(camada_oculta_teste)
camada_saida_teste = tf.add(tf.matmul(camada_oculta_ativacao_teste, W_final['saida']), b_final['saida'])
camada_saida_ativacao_teste = tf.sigmoid(camada_saida_teste)

In [16]:
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(camada_saida_ativacao_teste, feed_dict={xph: X}))



[[0.96563125]
 [0.04693902]
 [0.02018708]
 [0.95624864]]
